- name: Checks that all items contains the proper fields
  fail:
    msg: "The field {{ item.0 }} must be present in all mcb_backup_crons entries"
  when: "item[1][item.0] is undefined"
  with_nested:
    - [ "day", "hour", "minute", "name", "source", "destination", "port"]
    - "{{ mcb_backup_crons }}"